// <auto-generated />
using System;
using Food4You.Services.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Food4You.Services.Migrations
{
    [DbContext(typeof(Food4YouContext))]
    [Migration("20230808135618_inicijalna")]
    partial class inicijalna
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Food4You.Services.Database.Drzava", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Drzava__3214EC077B24F9AE");

                    b.ToTable("Drzava", (string)null);
                });

            modelBuilder.Entity("Food4You.Services.Database.Grad", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Grad__3214EC0703D5B88E");

                    b.ToTable("Grad", (string)null);
                });

            modelBuilder.Entity("Food4You.Services.Database.Kategorija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Opis")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Kategori__3214EC07F4A4B1B1");

                    b.ToTable("Kategorija", (string)null);
                });

            modelBuilder.Entity("Food4You.Services.Database.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DrzavaId")
                        .HasColumnType("int");

                    b.Property<int?>("GradId")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KorisnickoIme")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LozinkaHash")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LozinkaSalt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prezime")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Korisnik__3214EC079965D60E");

                    b.HasIndex("DrzavaId");

                    b.HasIndex("GradId");

                    b.ToTable("Korisnik", (string)null);
                });

            modelBuilder.Entity("Food4You.Services.Database.KorisnikUloga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumIzmjene")
                        .HasColumnType("datetime");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int?>("UlogaId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Korisnik__3214EC07396D9064");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("UlogaId");

                    b.ToTable("KorisnikUloga", (string)null);
                });

            modelBuilder.Entity("Food4You.Services.Database.Meni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Cijena")
                        .HasColumnType("money");

                    b.Property<int?>("KategorijaId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slika")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Meni__3214EC07AB24D271");

                    b.HasIndex("KategorijaId");

                    b.ToTable("Meni", (string)null);
                });

            modelBuilder.Entity("Food4You.Services.Database.Narudzba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumNarudzbe")
                        .HasColumnType("datetime");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("StateMachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusNarudzbeId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Narudzba__3214EC077DAAB08D");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("StatusNarudzbeId");

                    b.ToTable("Narudzba", (string)null);
                });

            modelBuilder.Entity("Food4You.Services.Database.NarudzbaStavke", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Cijena")
                        .HasColumnType("money");

                    b.Property<int?>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int?>("MeniId")
                        .HasColumnType("int");

                    b.Property<int?>("NarudzbaId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Narudzba__3214EC07CF813CCB");

                    b.HasIndex("MeniId");

                    b.HasIndex("NarudzbaId");

                    b.ToTable("NarudzbaStavke", (string)null);
                });

            modelBuilder.Entity("Food4You.Services.Database.Recenzije", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int?>("MeniId")
                        .HasColumnType("int");

                    b.Property<int?>("Ocjena")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Recenzij__3214EC0775C908A4");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("MeniId");

                    b.ToTable("Recenzije", (string)null);
                });

            modelBuilder.Entity("Food4You.Services.Database.StatusNarudzbe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__StatusNa__3214EC07AFE0E716");

                    b.ToTable("StatusNarudzbe", (string)null);
                });

            modelBuilder.Entity("Food4You.Services.Database.Uloga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Uloga__3214EC07F993517F");

                    b.ToTable("Uloga", (string)null);
                });

            modelBuilder.Entity("Food4You.Services.Database.Uplatum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrojTransakcije")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DatumTransakcije")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Iznos")
                        .HasColumnType("money");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Uplata__3214EC07FEFF0C35");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Uplata");
                });

            modelBuilder.Entity("Food4You.Services.Database.Korisnik", b =>
                {
                    b.HasOne("Food4You.Services.Database.Drzava", "Drzava")
                        .WithMany("Korisniks")
                        .HasForeignKey("DrzavaId")
                        .HasConstraintName("FK__Korisnik__Drzava__71D1E811");

                    b.HasOne("Food4You.Services.Database.Grad", "Grad")
                        .WithMany("Korisniks")
                        .HasForeignKey("GradId")
                        .HasConstraintName("FK__Korisnik__GradId__70DDC3D8");

                    b.Navigation("Drzava");

                    b.Navigation("Grad");
                });

            modelBuilder.Entity("Food4You.Services.Database.KorisnikUloga", b =>
                {
                    b.HasOne("Food4You.Services.Database.Korisnik", "Korisnik")
                        .WithMany("KorisnikUlogas")
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("FK__KorisnikU__Koris__76969D2E");

                    b.HasOne("Food4You.Services.Database.Uloga", "Uloga")
                        .WithMany("KorisnikUlogas")
                        .HasForeignKey("UlogaId")
                        .HasConstraintName("FK__KorisnikU__Uloga__778AC167");

                    b.Navigation("Korisnik");

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("Food4You.Services.Database.Meni", b =>
                {
                    b.HasOne("Food4You.Services.Database.Kategorija", "Kategorija")
                        .WithMany("Menis")
                        .HasForeignKey("KategorijaId")
                        .HasConstraintName("FK__Meni__Kategorija__4E88ABD4");

                    b.Navigation("Kategorija");
                });

            modelBuilder.Entity("Food4You.Services.Database.Narudzba", b =>
                {
                    b.HasOne("Food4You.Services.Database.Korisnik", "Korisnik")
                        .WithMany("Narudzbas")
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("FK__Narudzba__Korisn__7D439ABD");

                    b.HasOne("Food4You.Services.Database.StatusNarudzbe", "StatusNarudzbe")
                        .WithMany("Narudzbas")
                        .HasForeignKey("StatusNarudzbeId")
                        .HasConstraintName("FK__Narudzba__Status__7C4F7684");

                    b.Navigation("Korisnik");

                    b.Navigation("StatusNarudzbe");
                });

            modelBuilder.Entity("Food4You.Services.Database.NarudzbaStavke", b =>
                {
                    b.HasOne("Food4You.Services.Database.Meni", "Meni")
                        .WithMany("NarudzbaStavkes")
                        .HasForeignKey("MeniId")
                        .HasConstraintName("FK__NarudzbaS__MeniI__00200768");

                    b.HasOne("Food4You.Services.Database.Narudzba", "Narudzba")
                        .WithMany("NarudzbaStavkes")
                        .HasForeignKey("NarudzbaId")
                        .HasConstraintName("FK__NarudzbaS__Narud__01142BA1");

                    b.Navigation("Meni");

                    b.Navigation("Narudzba");
                });

            modelBuilder.Entity("Food4You.Services.Database.Recenzije", b =>
                {
                    b.HasOne("Food4You.Services.Database.Korisnik", "Korisnik")
                        .WithMany("Recenzijes")
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("FK__Recenzije__Koris__04E4BC85");

                    b.HasOne("Food4You.Services.Database.Meni", "Meni")
                        .WithMany("Recenzijes")
                        .HasForeignKey("MeniId")
                        .HasConstraintName("FK__Recenzije__MeniI__03F0984C");

                    b.Navigation("Korisnik");

                    b.Navigation("Meni");
                });

            modelBuilder.Entity("Food4You.Services.Database.Uplatum", b =>
                {
                    b.HasOne("Food4You.Services.Database.Korisnik", "Korisnik")
                        .WithMany("Uplata")
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("FK__Uplata__Korisnik__07C12930");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("Food4You.Services.Database.Drzava", b =>
                {
                    b.Navigation("Korisniks");
                });

            modelBuilder.Entity("Food4You.Services.Database.Grad", b =>
                {
                    b.Navigation("Korisniks");
                });

            modelBuilder.Entity("Food4You.Services.Database.Kategorija", b =>
                {
                    b.Navigation("Menis");
                });

            modelBuilder.Entity("Food4You.Services.Database.Korisnik", b =>
                {
                    b.Navigation("KorisnikUlogas");

                    b.Navigation("Narudzbas");

                    b.Navigation("Recenzijes");

                    b.Navigation("Uplata");
                });

            modelBuilder.Entity("Food4You.Services.Database.Meni", b =>
                {
                    b.Navigation("NarudzbaStavkes");

                    b.Navigation("Recenzijes");
                });

            modelBuilder.Entity("Food4You.Services.Database.Narudzba", b =>
                {
                    b.Navigation("NarudzbaStavkes");
                });

            modelBuilder.Entity("Food4You.Services.Database.StatusNarudzbe", b =>
                {
                    b.Navigation("Narudzbas");
                });

            modelBuilder.Entity("Food4You.Services.Database.Uloga", b =>
                {
                    b.Navigation("KorisnikUlogas");
                });
#pragma warning restore 612, 618
        }
    }
}
